### ISSUE TITLE
Split speeds disappear when leaving a map

### ISSUE THREAD

**Issue by tmenjoyah** [RuurdBijlsma/tm-split-speeds#11]
Not sure if anyone else has this issue, but I've searched everywhere and can't find any info about it. Whenever I get a new pb, my split speeds work, but whenever I leave the map and come back, my split speeds are gone and I need to set a new pb to get split speeds back, and then the same issue persists again if I leave the map.

Any fix for this? Is it a known problem? 

Any help would be appreciated.

**Comment by RuurdBijlsma** [comment]
Yea I know about this. Haven't had the time lately to work on the plugin sadly. I have started working on a fix but idk when I can finish it
