### ISSUE TITLE
not saving speeds at all with rally update

### ISSUE THREAD

**Issue by ezio416** [RuurdBijlsma/tm-split-speeds#12]
No new files have been created in PluginStorage since the update (2024-02-26_11_36), even on maps with no rally transformation

**Comment by ezio416** [comment]
oddly enough it worked on the COTD server just not solo it seems

**Comment by RuurdBijlsma** [comment]
i fixed it, but we have to wait for it to be reviewed before i can publish it

**Comment by ezio416** [comment]
Yeah seems to be working again, thank you!

**Comment by RuurdBijlsma** [comment]
The update went live 7 hours ago but if it works it works

**Comment by RuurdBijlsma** [comment]
oo nice
