### ISSUE TITLE
shown on main loading screen

### ISSUE THREAD

**Issue by ezio416** [RuurdBijlsma/tm-split-speeds#14]
I'm guessing this should be an easy fix, but since the last update it's showing for a few seconds upon game boot:

![Screenshot 2024-03-01 105939](https://github.com/RuurdBijlsma/tm-split-speeds/assets/37951898/bcfa3002-82f4-48ac-8222-20a9a4cb15ae)

**Comment by RuurdBijlsma** [comment]
fixed it thx
