### ISSUE TITLE
Split times?

### ISSUE THREAD

**Issue by MrCurlyHead** [RuurdBijlsma/tm-split-speeds#17]
Is it easy to add split times and not just split speeds? For ranked races in the career tracks theres no split times at CPs. I was wondering if a new plugin would need to be created or if it use to be apart of this plugin

**Comment by RuurdBijlsma** [comment]
This would be a separate plugin since it's not really I the scope of split speeds.

I personally dont spend a lot of time developing plugins anymore. I just maintain this, so I wouldn't be the one to make this.
