### ISSUE TITLE
Add exports for current data

### ISSUE THREAD

**Issue by XertroV** [RuurdBijlsma/tm-split-speeds#3]
It'd be nice if other plugins could use the data split speeds collects and displays.

From looking at things, it might be sufficient to add some functions exporting the values in `GUI` that get used while drawing. e.g.,
```
    float currentSpeed = 0;
    float difference = 0;
    uint showTime = 0;
    bool hasDiff = false;
    bool visible = true;
```

Those might not be sufficient (not sure), but are a good start. 

Note: please don't use the filenames `Export.as` or `ExportShared.as` -- there's an issue in openplanet atm where, if two dependencies have overlapping exported filenames, one of them overrides the other and you get compile errors. (Only happens with .op files) -- the safe way to handle this is prefix your export files with something like `SS_`.

**Comment by RuurdBijlsma** [comment]
👌  https://github.com/RuurdBijlsma/tm-split-speeds/commit/96145c0e9245d028c23e58295574b8a1af0365fb
