### ISSUE TITLE
Split speeds don't show when crossing the finish (sometimes it also doesn't show when crossing checkpoints)

### ISSUE THREAD

**Issue by oMqngo** [RuurdBijlsma/tm-split-speeds#8]
Hello,

I used to get the issue where whenever I crossed the finish line, the split speeds wouldn't show. Ever since the latest update this hasn't happend anymore so I assumed it was fixed, but today the issue returned again. This time however, it doesn't show on both crossing the finish and crossing checkpoints. Then, whenever you drive a personal best it would start showing again. 

During the period that it wasn't working (with the latest update installed), i tried relaunching the plugin but this didnt fix it. There are also no errors in the log.

Any advice?

**Comment by ezio416** [comment]
This issue is still present when crossing a multilap finish, but only when starting a new lap. Finishing seems fine

**Comment by ezio416** [comment]
@RuurdBijlsma please reopen this issue as this is still a problem

**Comment by ezio416** [comment]
I've implemented a fix which I think is satisfactory. The problem was simply that the UI sequence could switch to finish before the plugin noticed I had taken another landmark.

**Comment by RuurdBijlsma** [comment]
> I've implemented a fix which I think is satisfactory. The problem was simply that the UI sequence could switch to finish before the plugin noticed I had taken another landmark.

I merged and uploaded to openplanet, will be published when it's approved
