### ISSUE TITLE
Update broke the plugin

### ISSUE THREAD

**Issue by Kaishidow** [RuurdBijlsma/tm-split-speeds#9]
Plugin does not show up on screen

**Comment by RuurdBijlsma** [comment]
works for me

**Comment by RuurdBijlsma** [comment]
do you get an error? in the log? you get log by pressing openplanet > log in the top bar

**Comment by BodyMovement** [comment]
Speed splits seem to work for stadium car, but any checkpoint driven through in snow car shows no speed splits. In the Winter 2024 campaign at least. No errors logged either.

**Comment by dudeofawesome** [comment]
I’m seeing this as well. The logs indicate that times are being saved to disk, and loaded from disk, but it looks like they do not include any checkpoints. 
![IMG_2847](https://github.com/RuurdBijlsma/tm-split-speeds/assets/1683595/4475e32d-1dbd-4a1b-9a95-f4ed0359b67c)

(Sorry for the photo, I’m playing on Steam Deck, so wasn’t sure how to take a proper screenshot)

As you can see, the logs report “cp count: 0”

**Comment by RuurdBijlsma** [comment]
this was an issue with the vehiclestate dependency which is part of openplanet, and it has been fixed now
